# DataSource Configuration
spring.datasource.url=jdbc:postgresql://dpg-d6r7jendiees73c3igbg-a.singapore-postgres.render.com/hn369_ecommerce_h13v
spring.datasource.username=hn369_ecommerce_h13v_user
spring.datasource.password=ww5UaFyXMyIG1UcgJAOACFlMCUPU6WMN
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

cors.allowed.origins=https://online-code-formatter.com
cors.allowed.methods=GET,POST,PUT,DELETE,OPTIONS
cors.allowed.headers=*
cors.allow-credentials=true
cors.max-age=3600